### ISSUE TITLE
SmartPy developers can continuously develop applications with complex smart contracts

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#1061]
- [ ] Multi-file smart contract projects can be compiled, tested, and deployed
- [ ] Advanced sample smart contracts can be opened, compiled, tested, and deployed
- [ ] Ability to execute tests as part of CI/CD
- [ ] Full contract metadata, including off-chain views and errors

**Comment by hu3man** [comment]
Belongs in PB
