### ISSUE TITLE
Check for Taq'fied projects

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#108]
As a user, I want to be prevented from initializing a Taqueria project instance multiple times so that I do not overwrite my project.

#### Acceptance Criteria
- [ ] If a previously initialized project is initialized again, return a message saying the project is already Taq'fied - `The project is already taqified`
- [x] If a previously initialized project is initialized again, do not re-initialize the folder
- [ ] Hide the option to change the configuration directory in CLI
- [ ] Works in both CLI and VS Code extension
- [x] Documentation is created and updated #283

#### Sub-tasks
- [x] #382
- [x] #381

**Comment by russellmorton** [comment]
Documentation to be updated:

- Add information to Quick Start highlighting that the project cannot be initialized multiple times

**Comment by hu3man** [comment]
> 

So am I understanding correctly? 
1. We need to detail that currently, re-initializing a project will wipe out the config and state 
2. When this feature is released, that messaging will no longer be required

**Comment by hu3man** [comment]
@russellmorton , should we just close this?

**Comment by russellmorton** [comment]
Yes, the config does not get overwritten so there is no risk to the user anymore. We can look at adding this again later.
