### ISSUE TITLE
[🌮 Epic|Feature]: 

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1150]
### Status

- [ ] 💡 Feature Design
- [X] 🧪 Testing Plan
- [ ] 🔪 Ticket Slicing
- [ ] 🥂 Feature Complete

### Feature Description

xyz

### 🔍  Feature 
- [ ] 
 
 ### 📚 Documentation 
- [ ] New feature docs 
- [ ] Refactor existing docs 
- [ ] Release notes 
- [ ] 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
