### ISSUE TITLE
🚧 Dev ➾  Refactor all tasks to use hyphens

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1159]
### Ticket Status

- [X] 🔬 Planning and Design
- [ ] 💻 Dev Implementation
- [ ] 🤖 Automated Tests
- [ ] 📚 Documentation

### Behaviour
 - [ ] All plugin tasks are refactored to be hyphen separated
 - [ ] VSCE is updated to support the changes

### Testing
- [ ] All unit tests affected by the refactor are updated
- [ ] Extensive manual testing of VSCE
- [ ] Extensive manual testing of CLI

### Documentation
- [ ] Update plugin docs in `.eta` files ( located in plugin directory`taqueria/taqueria-plugin-ligo/readme.eta)
- [ ] Update all other docs in /website/docs folder (excluding /plugins since those docs are build from the eta files
- [ ] A summary of which tasks have changed is written for the release notes

### To Do

Planning:
- [ ] Identify all tasks needing to be updated (add to ticket below)
- [ ] Identify how these changes will impact VSCE ( add to ticket below)

Implementation:
- [ ] Refactor task names
- [ ] Get CLI working (expecting tests to fail)
- [ ] Fix automated tests
- [ ] Fix VSCE issues
- [ ] Refactor docs 

### Task Description

Currently, Taqueria uses some multi-word tasks that are space separated, rather than hyphen-separated (eg `taq start sandbox`)

This ticket involves refactoring those commands to use hyphens, rather than spaces:
E.g. `taq start sandbox local` will become `taq start-sandbox local`

This change affects all plugins, the CLI, VSCode extension, and e2e tests and will be handled in this work unit

### Test Plan

This refactor will ensure that all existing tests are updated to support the changes. There will also need to be extensive manual testing on those updated tasks to ensure that edge cases and bugs are identified and handled

### Sizing

5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
