### ISSUE TITLE
🚧 Dev Task: [EPIC] Implement Sandbox Baking Options

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1162]
### 🚥 Definition of Done

- [X] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation (PR merged)
- [ ] ✍️ Release Notes Added
- [ ] 🏆 Product Acceptance

### ✅ To Do

- [x] Meet with Jev and Dan to understand mempool and endpoint options

1. Implement manual baking task
2. Develop long-lived task that provides bake-on-demand functionality
3. Implement custom block time

Options:
- Manual baking 
- Auto baking

### ⚖️ Acceptance Criteria

✨ Functional: 

- [x] Add a task to bake a block `taq bake`
- [x] Flextesa plugin can have a custom block time specified by the user 
- [ ] Auto-bake (bake a block as soon as an operation is injected and only when operation injected)

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- Work on Taqueria/plugins other than Flextesa
 
### 🧰 Work Description

Flextesa needs to support various sandbox baking options such as bake-on-demand, auto-bake, and a configurable block time. This will improve the developer experience

For auto bake, the options are:

- mempool pull
- proxy

Auto-bake 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment]
Done
