### ISSUE TITLE
🚧 Dev ➾ Add automated tests for IPFS-Pinata plugin

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1164]
### Ticket Status

- [x] 🔬 Planning and Design
- [ ] 💻 Dev Implementation
- [ ] 🤖 Automated Tests
- [ ] 📚 Documentation

### Acceptance Criteria

- [ ] Help contents
- [ ] Credentials for pinata (different types of API keys and settings)
- [ ] Different file types we expect people to upload? Uploading a directory as opposed to single/multiple files
- [ ] Any limits placed on the Pinata account key
- [ ] Ensuring that there is an account CI tests can use for uploading files
- [ ] Uploading already uploaded files to update / what happens when multiple files are uploaded but one/multiple fails

### Task Description

We should have automated tests to ensure that the IPFS-pinata taq plugin is functioning as expected

### Sizing

5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Done!
