### ISSUE TITLE
[🌮 Epic|Feature]: Let users know there is a new version of Taqueria available

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1165]
### Status

- [ ] 💡 Feature Design
- [ ] 🧪 Testing Plan
- [ ] 🔪 Ticket Slicing
- [ ] 🥂 Feature Complete

### Feature Description

Taqueria should periodically check to see if there is a newer version available. If there is, Taqueria should inform the user and provide an easy means to upgrade

### Problem or Use Case

As you can see in this image, only 12% of Taqueria users are on a recent version. We still have almost 40% of users using v0.6.5 which know bugs

With the rapid pace of development, Taqueria needs a way to help users keep up to date with the most recent improvements. This will also dramatically decrease the incidence of bugs related to plugin/binary version mismatch

![Screen Shot 2022-08-19 at 8 36 38 PM](https://user-images.githubusercontent.com/32914364/185727511-d4b2ecf7-0465-4364-b01a-cd9d653d76bb.png)
o

### Acceptance Criteria

- [ ] The CLI has the means to check for the most recent version of Taqueria
- [ ] A periodic check is implemented and upon a newer release version being found, the user is informed with an actionable message
- [ ] (stretch goal) Taqueria can automatically download and install the newer binary upon user approval

### Sizing

2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Closing: will cover as part of a health check ticket
