### ISSUE TITLE
🚧 Dev Epic ➾ Ligo Dev WF Improvements (user requests)

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1166]
### Epic|Feature Link: #1167 
https://ecadlabs.productboard.com/feature-board/5219572-taqueria-features/features/14699515

### 🚥 Definition of Done

- [x] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation
- [ ] 🏁 Test Plan Executed
- [ ] 🛩️ Documentation Updated
- [ ] 🏟️ Peer / User Reviewed
- [ ] 🏆 Validated and Accepted

### 🔭 Scope

🏎️ In Scope: 
 - [ ] 

 🙅‍♂️ Out of Scope: 
 - [x]  

### 🧰 Work Description

PLESAE UPDATE ME!

### Features
- [ ] #1340
- [ ] #1341
- [x] #1343
- [ ] Ligo Native Tests
- [x] Update simulate task

### Requirements
- [ ] Default to compiling to a file
- [ ] Should be annotation aware

### 🐘 Sizing

0.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment]
Todo: @hu3man / @jchenche , follow up with LIGO team to determine why they requested version pinning and confirm that using a min/max approach would worko

**Comment by hu3man** [comment]
Closing as complete
