### ISSUE TITLE
🚧 Dev ➾ [EPIC] VScE Micheline Editor / Entrypoint Invocation UI Improvements

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1370]
### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation (PR merged)
- [ ] ✍️ Release Notes Added
- [ ] 🏆 Product Acceptance

### ✅ To Do

- [ ] Store state from editor when moving between tabs
- [ ] Add support for views
- [ ] Provide a means for the entrypoint to be invoked from one of the declared accounts
- [ ] Add another component which shows the user the Michelson type
- [ ] Deletion of objects
- [ ] Support changing order
- [ ] Add data Validation
- [ ] Add more information about the contract and entrypoint to the display
- [ ] Show the user a cleanly rendered view of the type
- [ ] Provide a means to copy/paste the output json from the UI
- [ ] The ability to specify parameter values in high level languages
- [ ] As these operations are proxying to the CLI, what if it an account being used has a type of BeaconWalletAccount? 
- [ ] Find help in ECAD for polishing the CSS styling of the form
- [ ] 2 Way data flow between diagnostics and form

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] ... 
 
 📐 Non-Functional: 
- [ ] ... 
 

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### 🧰 Work Description

Working ticket for ideas to improve the UI and UX for the VsCE Micheline editor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
