### ISSUE TITLE
🐛 Bug ➾ Taco-shop scaffold tests have internal ECAD Todo note published

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1502]
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I was looking at the tests for the taco-shop scaffold to see why 2 were failing, and I noticed a note:

        // TODO: Talk with Alex about this one
        // const sandboxContractContents = await execPromise(`curl http://localhost:20000/chains/main/blocks/head/context/contracts/${contractHash}`)
        // expect(sandboxContractContents.stdout).toContain('"storage":{"int":"42"}')

This should not have a personal name reference; in fact, there should be no TODO or commented prospective code in a published project.

### 🆘 Steps to Reproduce?

1. in the Taco-Shop Scaffold, look at file  ~/taco-shop/tests/taqueria.spec.ts
2. observe the TODO

### 🐘 How impactful is this bug?

🐜 Minor annoyance

### ⏱️ Prevalance

If they read the file

### 💻 Operating System

Windows -> Linux VM

### 🌮 Taqueria Version

v0.24.1

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
