### ISSUE TITLE
Jest Testing Plugin

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#457]
As a smart contract developer, I want to test my smart contracts using a Taqueria plugin so that I have an easy way to start testing my project.

Layers of testing:

- Unit level native testing on contract done at compile time
- Jest plugin for integration and end to end tests

**ADDITIONAL INFORMATION**
The testing plugin should focus on the interaction with the chain.

**USER STORIES:**
- [x] #540
- [x] #524
- [ ] #572 
- [x] #788
- [ ] #792
- [ ] #789
- [ ] #790
- [x] #791
- [ ] As an SDET, I want complete coverage for the generated test stubs so that the team can be confident that test stub generation correctly and comprehensively converts all entry points in all Michelson contracts into TS/JS test stubs 
- [ ] As a newcomer dev, I would like a guide to best practices that includes examples of how to implement the test stubs so that I can get up and running with my tests.
- [ ] As a newcomer dev, I want taqueria to handle dependent plugins so that I do not have to manually handle these dependencies.
- [x] #525

Some tests:
- Test to assure that the test stubs match what's expected
- Test to assure that the test stubs work - they actually produce the expected test output

**ACCEPTANCE CRITERIA**
- [ ] Create a testing framework - how to run different tests for your project
 - [ ] Test directory with Jest test suites and Taqueria will run them
 - [ ] Test task will come from a Jest plugin
 - [ ] NPM distribution
 - [ ] Jest assertion library
 - [ ] Custom assertion library for Taqueria
- [ ] Current sandbox
  - [ ] Library to start and stop sandbox
- [ ] `taq test` will run all tests
- [ ] Hooks for dapp specific tests
- [ ] Types of tests
  - [ ] smart contract functionality
  - [ ] project tests (dapp)
- [ ] Example tests - part of scaffolding and "Hello World"
- [ ] Support tests in Typescript and Javascript - default to Typescript with support for vanilla JS
- [ ] Tests should be environment/protocol-agnostic (common identifier maps to correct address in all environments)
- [ ] Keygen/wallet abstraction layer should allow the user to configure pre-funded test accounts that can be used for testnet operations
- [ ] API for running integration and end to end tests

_Defer invocation of the app-specific tests_

**Comment by russellmorton** [comment]
Should `taq test` run tests for your dapp?

**Comment by russellmorton** [comment]
describe () {
  before() {
   startSandbox()
  }
  test( () => {
     ...
  })

after( () => {
  stopSandbox();
});
}
