### ISSUE TITLE
Initial implementation of state registry - Origintated accounts (EPIC - should not be on board)

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#617]
As a smart contract developer, I want to be able to track originated accounts (KT1 addresses) in a state registry so that I can reference them by name

**USE CASES**
- As a developer, I want to be able to reference the address of an originated contract by some kind of identifier and have that identifier persist for the lifetime of the environment unless I explicitly remove it
- As a developer, I want to be able to refer to another smart contract address in the initial storage of another contract. without the address being hardcoded.
- As a tester, I want to be able to refer to originated accounts in my test cases without hardcoding the addresses.

**MVP**
- [x] #721

**DEFERED**

**TICKETS**
- [x] #620
- [x] #593
- [x] #621
- [x] #622
- [x] #623

**ACCEPTANCE CRITERIA**
- [x] Persistent state is recorded in the state for the project (whatever outputs are generated from originating a contract (k: taquito.originate.operationName v: address, timestamp)
- [ ] Abstraction layer to track the name of the name of the contract to the originated address
- [x] Running the command `taq originate` will implicitly create an operation for the user and execute it

**OUT OF SCOPE**
- Generating accounts on demand
- Support for global constants
- Support for tickets
- #544 
- #545 
- #546 

**REFERENCE**
https://github.com/ecadlabs/taqueria/blob/main/design-docs/state-architecture.md

**RELATED**
- #549 
- #210

**Comment by mweichert** [comment]
The above use-cases will be implemented as such:
- [ ] Operation construct needs to be developed
- [ ] An operation called 'originate' will be exposed from the Taquito plugin
- [ ] A new core task called "taq apply" will be developed to apply the operations.

This provides a very minimal implementation and requires the end-developer to create operations manually. When templates and hooks are implemented, a user should just have to create a contract from an existing template, and the operations will be created automatically via hooks.

Note, for existing contracts

Note,
