### ISSUE TITLE
As an SRE, I want to be able to run Taqueria inside Github actions so that I can improve consistency by using Taqueria tasks and plugins as part of my CI/CD pipeline

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#644]
As a Taqueria user, I want to have a docker image with Taqueria and all plugins available via GitHub actions so that I can run any Taqueria commands as part of my CICD process.

- List of tasks and arguments to run against the binary
- Authoring in yaml
- Configure GitHub action with parameters
- Action can be registered on a commit and can execute a Taqueria task or list of tasks
`{
  task: "compile",
  sourceFile: "increment.tz"
}`
- Pass config and project directory to the Docker image
- Task and environment defined by the user

**USE CASE**
As part of CICD - build an app and compile contracts

**TICKETS**
- [x] #660
- [x] #661

**ACCEPTANCE CRITERIA**
- [x] State file resides in the repo
- [x] Initialized project exists in Docker image
- [x] Pass environment as part of yaml (set to testing environment by default)
- [x] Docker image built based on the yaml config file
- [x] Common use case templates defined

**Comment by GImbrailo** [comment]
@mweichert @russellmorton GitHub requires the action to be in it's own repository to publish to the GitHub Marketplace. Will this be an issue or can I go ahead and create that repository?

**Comment by russellmorton** [comment]
I don't see an issue with it being in it's own repo.

**Comment by hu3man** [comment]
Ya I think it's fine for it to be in a separate repo

**Comment by GImbrailo** [comment]
@hu3man @russellmorton @mweichert the GtiHub action is available in [this repo](https://github.com/ecadlabs/taqueria-github-action). Please have a look and let me know if you are able to test it out in a project or branch.

In that repo I have two workflows that test two different projects. One of them creates a new project using just a config file and contract in the root directory and the other builds and tests the [hello-tacos](https://github.com/ecadlabs/hello-tacos) project. 

Here is one of the runs for the project in the root directory https://github.com/ecadlabs/taqueria-github-action/actions/runs/2393749913

Here is a run for the `hello-tacos` project https://github.com/ecadlabs/taqueria-github-action/actions/runs/2393749914

**Comment by hu3man** [comment]
Hey @GImbrailo, this looks great! The options, structure, run output, and log output look good to me 

I have a few questions about the best way to use this on a project, as well as a few of the steps like the artifact upload but that may just be due to my limited understanding of GH actions (coming from a Jenkins world here!)

Would you be able to give me an overview and a bit of direction on best practices and what to document in a 30min sync soon?

**Comment by hu3man** [comment]
Are we planning on releasing this action on the github marketplace @GImbrailo @russellmorton ?
https://github.com/marketplace?category=&query=&type=actions&verification= 

For reference, instructions are here:
https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions

**Comment by russellmorton** [comment]
@hu3man @GImbrailo, please include me on that call?

Yes, I think it would be ideal to publish this action on the marketplace. @GImbrailo, let me know what you need to get this done.

**Comment by GImbrailo** [comment]
@russellmorton @hu3man After having the demo with Jev I think this issue can be closed and we can make a beta release of the action for internal use maybe? I think a new issue needs to be created to refactor the action and the following needs to be included:

- [ ] Documentation on how to use the action
- [ ] Integration with the Taqueria release flow
- [ ] The action needs to report usage to Google Analytics so that we can see where it is being used in CI

I also need someone to use the action in a project or workflow to get more feedback

**Comment by hu3man** [comment]
Awesome news, thanks for the detailed closing update @GImbrailo! 👌

Please go ahead and open that ticket (assign it to iteration #8)

I think your idea about a soft(internal) beta launch is a great idea. I'd love to start using it on the new scaffold mono-repo (github.com/ecadlabs/taqueria-scaffolds). What are the next steps required to be that beta release?

**Comment by russellmorton** [comment]
#865 created
