### ISSUE TITLE
Taqueria CLI UX Improvements

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#866]
### Describe the feature you would like

**User story:** 
As a user, I want the Taqueria CLI to be fun to use, visually appealing, and intuitive so that I can have a joyful Tezos development experience and troubleshoot Taqueria CLI issues without leaving the command line

Items for refactoring:
- [ ] Since running taq --help right after a plugin installation does not update the list of available tasks (horrible UX), can we implement our own version that does? taq -h or something like that maybe
- [ ] Right now if you run taq with no arguments, you get an error stating Your config.json file is invalid. This should show something like `You are running taq in a directory that is not a Taqueria project`
- [ ] Periods should be removed from CLI output statements
- [ ] Colour should be added where appropriate to indicate success/failure
- [ ] Add emoji's where possible to make the interface more fun
- [ ] Provide the exact command the user should run to fix the output encountered (if origination fails because the sandbox isn't started, tell the user they need to run `taq start sandbox local`
- [ ] Re-order the error output from the CLI to appear above the menu options (it's currently is hard to see what the actual error output is
- [ ] Make the Zod errors more friendly (message instead of: [object] [object] is invalid)
- [ ] Refactor CLI output phrases to be as fun and friendly as possible
- [ ] Explore adding additional aliases for power users (`taq ss` for start sandbox)
- [ ] Refactor `taq start sandbox <sandBoxName> to default to using the default sandbox if the user only runs `taq start sandbox`

### Is this feature solving a problem?

Currently, the messaging output for the CLI does not match the Taqueria brand identity and could use improvements to bring the look, feel, and tone in line with the target audience and brand identity

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
